<?= $this->renderTabs($this->tabs); ?>
<p>When running your Plesk server behind a proxy, such as a load balancer or a CDN, both access and error logs will not store the actual IP Address of your visitors.</p>
<p>Luckily, as this is a very common situation, nginx has a module called "realip" for solving this very problem. You can use this extension to configure the behavior of such module without having to manually write nginx configurations for each domain.</p>
<?= $this->form; ?>
